### ISSUE TITLE
Error parsing JSON

### ISSUE THREAD

**Issue by suzhouhu** [deepanshu88/chatgpt_PowerPoint#3]
![图片](https://github.com/deepanshu88/chatgpt_PowerPoint/assets/23079693/72d29358-c139-4156-bd7d-97b35ac39584)

**Comment by deepanshu88** [comment]
Try again. OpenAI API does not return output in JSON format sometimes. It is working fine at my end.

**Comment by suzhouhu** [comment]
Case Else
        ' Error: Invalid JSON string
        Err.Raise 10001, "JSONConverter", json_ParseErrorMessage(jsonString, json_Index, "Expecting '{' or '['")

**Comment by deepanshu88** [comment]
Can't replicate this issue. It's working fine at my end. Is chatgpt available in your country?
